### ISSUE TITLE
I install everything right. but when It comes to execution, it fails.

### ISSUE THREAD

**Issue by clarionsmith** [natolambert/blogcaster#11]
I install everything right. but when It comes to execution, it fails. I am exporting an article via Notion. I tried changing image file names and keeping them as it is. still same issue. Your workflow is beautiful and I have a use case for this for my magazine website. would want to use it. Please help.

<img width="642" alt="Screenshot 2024-03-16 at 1 23 31 AM" src="https://github.com/natolambert/interconnects-tools/assets/20444144/2bd24d8e-0c6e-4ffc-b45f-0a38e621c4bc">

**Comment by natolambert** [comment]
Awesome, glad you're trying this. Happy to help.
What system are you using? If not MacOS, I suspect accommodations may be needed.

Things to check too
* FFMpeg version
* operating system

**Comment by natolambert** [comment]
Also check the file `audio_00_09.mp3`, sometimes if there's an issue with 11labs API, the error isn't caught and it needs to be regenerated.

The audio file may have "0 seconds" or something. I've seen weird things but haven't always known why.

**Comment by natolambert** [comment]
@clarionsmith there's another path error too, as `No such file or directory` for `figure_01.mp3` (path issue? it should be automated)

**Comment by clarionsmith** [comment]
> Awesome, glad you're trying this. Happy to help.
> 
> What system are you using? If not MacOS, I suspect accommodations may be needed.
> 
> 
> 
> Things to check too
> 
> * FFMpeg version
> 
> * operating system

ffmpeg latest version
Operating system is MacOS

**Comment by clarionsmith** [comment]
> Also check the file `audio_00_09.mp3`, sometimes if there's an issue with 11labs API, the error isn't caught and it needs to be regenerated.
> 
> 
> 
> The audio file may have "0 seconds" or something. I've seen weird things but haven't always known why.

All audio files generated so not play. Even after regeneration, still same error. Yes, the files have no time. They neither are corrupted nor playable.

**Comment by natolambert** [comment]
Have you gotten the 11labs api working locally in some way? This for example happened to me when I ran out of characters in my plan and then I turned on "bill me for extra characters" and it worked.

**Comment by natolambert** [comment]
(may not get to adding tests and code for this until later next week, but adding checks for folks would be nice)

**Comment by natolambert** [comment]
For example, the style in video generation is hard coded, so I should make it easier for people to swap in their own system prompts.

**Comment by clarionsmith** [comment]
> Have you gotten the 11labs api working locally in some way? This for example happened to me when I ran out of characters in my plan and then I turned on "bill me for extra characters" and it worked.

I took the 5 dollar plan and I have 30000 characters available. Didn't check local testing of 11labs api

**Comment by natolambert** [comment]
Yeah it may be an API key issue.
A brief intro is in the readme https://github.com/natolambert/interconnects-tools?tab=readme-ov-file#api-keys--models, but a lot more resources are available online with some searching.

**Comment by clarionsmith** [comment]
I am just looking to get the audio basic to work. And I tried the subsequent commands and they all throw the same error. Just unable to figure out the issue. Would you want to look at my codebase? I can share the full folder with you and maybe you run locally on your system and let me know if it works. Or maybe you can share a working folder with me and I will just run it on my end replacing all the api keys.

**Comment by natolambert** [comment]
I'd suggest you working with 11labs docs / their support to make sure you can get an example working with API before adding the complexity of my tools https://elevenlabs.io/docs/introduction

**Comment by clarionsmith** [comment]
> I'd suggest you working with 11labs docs / their support to make sure you can get an example working with API before adding the complexity of my tools https://elevenlabs.io/docs/introduction

Sure. I'll try this and get back to you.

**Comment by clarionsmith** [comment]
Error: [Errno 2] No such file or directory: 'source/repeat/figure_01.mp3'
cp: source/repeat/figure_01.mp3: No such file or directory . 

Is the above figure_01.mp3 file generated automatically? I am unable to find in tts.py  . In fact there's no repeat folder in source when I cloned the repository.

**Comment by clarionsmith** [comment]
> > I'd suggest you working with 11labs docs / their support to make sure you can get an example working with API before adding the complexity of my tools https://elevenlabs.io/docs/introduction
> 
> Sure. I'll try this and get back to you.

API is working as desired here. Ran an api call with my key and voice id successfully.

**Comment by natolambert** [comment]
Ah, I think I know what will fix it, lemme push a quick patch.
Essentially, the code is supposed to save `figure_01.mp3` to a directory `repeat/`, but the code didn't automatically make that directory, so the file saving fails, and the copying gets that error.

(the idea with repeat is so you don't need to regenerate text you may say multiple times)

**Comment by natolambert** [comment]
with #12, I *think* it should fix it. Definitely still feels like beta software, so thanks for helping!

**Comment by clarionsmith** [comment]
<img width="1282" alt="Screenshot 2024-03-17 at 3 51 03 PM" src="https://github.com/natolambert/interconnects-tools/assets/20444144/b095d492-0ff1-482a-ba14-aee044287693">

Hi @natolambert , using your updated code, the first part runs of generating the repeat folder and the figure_01.mp3 , now does not throw any error. however, the next part of empty/corrupted generated audio files still exist. the files are created, but I think there's no data in that. it keeps showing error opening the input files which is for the generated empty audio files. so I guess the audio files are getting generated namesake, without any data on that. Please check this.

**Comment by natolambert** [comment]
You need to manually delete the files from when you called 11labs with an API key error or whatever @clarionsmith. It won't automatically overwrite / clean empty files.

I can improve the logic soon so that if the 11labs API request returns empty/error, this'll be avoided.

**Comment by clarionsmith** [comment]
> You need to manually delete the files from when you called 11labs with an API key error or whatever @clarionsmith. It won't automatically overwrite / clean empty files.
> 
> 
> 
> I can improve the logic soon so that if the 11labs API request returns empty/error, this'll be avoided.

Did this like what you said by manually cleaning it, used a completely different folder and also a completely different system. Still the audio files are not getting populated with content. The concatenation of these audio files fails. And then the subsequent errors. Please check this @natolambert

**Comment by natolambert** [comment]
Can you provide the files? `ffmpeg` is known to be a bit wild.
I think the issue is that the bitrate is hardcoded to the "creator" level subscription. Will take a bit to check.

**Comment by clarionsmith** [comment]
Hi @natolambert , I shared all the requisite files over your email.
